# Generated by Django 4.2.5 on 2023-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("teacher_id", models.IntegerField(primary_key=True, serialize=False)),
                ("teacher_name", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
            ],
        ),
    ]
