# Generated by Django 4.1 on 2023-09-27 09:44

from django.db import migrations, models
import grades.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('gradeId', models.IntegerField(primary_key=True, serialize=False)),
                ('examType', models.CharField(max_length=55)),
                ('maths', models.PositiveIntegerField(max_length=100, validators=[grades.models.validate_value])),
                ('english', models.PositiveIntegerField(max_length=100, validators=[grades.models.validate_value])),
                ('kiswahili', models.PositiveIntegerField(max_length=100, validators=[grades.models.validate_value])),
                ('physics', models.PositiveIntegerField(max_length=100, validators=[grades.models.validate_value])),
                ('biology', models.PositiveIntegerField(max_length=100, validators=[grades.models.validate_value])),
                ('chemistry', models.PositiveIntegerField(max_length=100, validators=[grades.models.validate_value])),
                ('history', models.PositiveIntegerField(max_length=100, validators=[grades.models.validate_value])),
                ('geography', models.PositiveIntegerField(max_length=100, validators=[grades.models.validate_value])),
                ('cre', models.PositiveIntegerField(max_length=100, validators=[grades.models.validate_value])),
            ],
            options={
                'ordering': ['gradeId'],
            },
        ),
    ]
