# Generated by Django 4.1 on 2023-09-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_grade_delete_grades'),
    ]

    operations = [
    ]
