# Generated by Django 4.2.5 on 2023-09-27 09:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "studentadmno",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MinValueValidator(1000)],
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("guardian_telephone", models.CharField(max_length=255)),
                ("guardian_email", models.CharField(max_length=255)),
                ("guardian_name", models.CharField(max_length=255)),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="classes.class"
                    ),
                ),
            ],
            options={"ordering": ["studentadmno"],},
        ),
    ]
